# Generated by Django 5.2.6 on 2025-09-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.DeleteModel(
            name='BikeImage',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
