# Generated by Django 5.2.6 on 2025-09-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evt_id', models.CharField(max_length=21)),
                ('evt_name', models.CharField(max_length=51)),
                ('evt_type', models.CharField(max_length=51)),
            ],
        ),
    ]
