# Generated by Django 5.2.6 on 2025-09-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_host_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='owner',
        ),
    ]
